site_name: Firestore v1.0.7+20181002
site_url: http://byron.github.io/google-apis-rs/google-firestore1-cli
site_description: A complete library to interact with Firestore (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/firestore1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_databases-operations-cancel.md', 'Projects', 'Databases Operations Cancel']
- ['projects_databases-operations-delete.md', 'Projects', 'Databases Operations Delete']
- ['projects_databases-operations-get.md', 'Projects', 'Databases Operations Get']
- ['projects_databases-operations-list.md', 'Projects', 'Databases Operations List']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-list.md', 'Projects', 'Locations List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

