site_name: Speech v1.0.7+20181005
site_url: http://byron.github.io/google-apis-rs/google-speech1_beta1-cli
site_description: A complete library to interact with Speech (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/speech1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['speech_asyncrecognize.md', 'Speech', 'Asyncrecognize']
- ['speech_syncrecognize.md', 'Speech', 'Syncrecognize']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

