site_name: webmasters v1.0.7+20180627
site_url: http://byron.github.io/google-apis-rs/google-webmasters3-cli
site_description: A complete library to interact with webmasters (protocol v3)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/webmasters3-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['searchanalytics_query.md', 'Searchanalytics', 'Query']
- ['sitemaps_delete.md', 'Sitemaps', 'Delete']
- ['sitemaps_get.md', 'Sitemaps', 'Get']
- ['sitemaps_list.md', 'Sitemaps', 'List']
- ['sitemaps_submit.md', 'Sitemaps', 'Submit']
- ['sites_add.md', 'Sites', 'Add']
- ['sites_delete.md', 'Sites', 'Delete']
- ['sites_get.md', 'Sites', 'Get']
- ['sites_list.md', 'Sites', 'List']
- ['urlcrawlerrorscounts_query.md', 'Urlcrawlerrorscounts', 'Query']
- ['urlcrawlerrorssamples_get.md', 'Urlcrawlerrorssamples', 'Get']
- ['urlcrawlerrorssamples_list.md', 'Urlcrawlerrorssamples', 'List']
- ['urlcrawlerrorssamples_mark-as-fixed.md', 'Urlcrawlerrorssamples', 'Mark As Fixed']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

