site_name: AnalyticsReporting v1.0.7+20181008
site_url: http://byron.github.io/google-apis-rs/google-analyticsreporting4-cli
site_description: A complete library to interact with AnalyticsReporting (protocol v4)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/analyticsreporting4-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['reports_batch-get.md', 'Reports', 'Batch Get']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

